/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import view.agenda.Adicionar_GUI;
import view.agenda.Alterar_GUI;
import view.agenda.Consulta_GUI;
import view.agenda.Excluir_GUI;

/**
 *
 * @author fpopo
 */
public class Menu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Menu_GUI
     */
    public Menu_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        panel1 = new java.awt.Panel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        consulta_agenda = new javax.swing.JMenuItem();
        Add_agenda = new javax.swing.JMenuItem();
        alterar_agenda = new javax.swing.JMenuItem();
        excluir_agenda = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        calc_btn = new javax.swing.JMenuItem();
        bloc_btn = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        help_btn = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Encerrar_btn = new javax.swing.JMenuItem();

        label2.setText("label2");

        label3.setText("label2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panel1.setLayout(null);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg.jpg"))); // NOI18N
        panel1.add(panelImage1);
        panelImage1.setBounds(0, 20, 400, 280);

        getContentPane().add(panel1);
        panel1.setBounds(0, -20, 400, 300);

        jMenu1.setText("Agenda");

        consulta_agenda.setText("Consultar");
        consulta_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_agendaActionPerformed(evt);
            }
        });
        jMenu1.add(consulta_agenda);

        Add_agenda.setText("Adicionar");
        Add_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_agendaActionPerformed(evt);
            }
        });
        jMenu1.add(Add_agenda);

        alterar_agenda.setText("Alterar");
        alterar_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_agendaActionPerformed(evt);
            }
        });
        jMenu1.add(alterar_agenda);

        excluir_agenda.setText("Excluir");
        excluir_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_agendaActionPerformed(evt);
            }
        });
        jMenu1.add(excluir_agenda);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Paciente");

        calc_btn.setText("Cadastrar");
        calc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_btnActionPerformed(evt);
            }
        });
        jMenu2.add(calc_btn);

        bloc_btn.setText("Consultar");
        bloc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloc_btnActionPerformed(evt);
            }
        });
        jMenu2.add(bloc_btn);

        jMenuItem2.setText("Alterar");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Consulta");

        jMenuItem1.setText("Cadastrar");
        jMenu6.add(jMenuItem1);

        jMenuItem6.setText("Historico");
        jMenu6.add(jMenuItem6);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("History log");
        jMenuBar1.add(jMenu5);

        jMenu4.setText("Help");

        help_btn.setText("Arquivo");
        help_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_btnActionPerformed(evt);
            }
        });
        jMenu4.add(help_btn);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Sair");

        Encerrar_btn.setText("Encerrar");
        Encerrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Encerrar_btnActionPerformed(evt);
            }
        });
        jMenu3.add(Encerrar_btn);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Encerrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Encerrar_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Encerrar_btnActionPerformed

    private void help_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_btnActionPerformed
        try {
            Runtime.getRuntime().exec("cmd.exe /c start C:\\Users\\fpopo\\OneDrive\\Área de Trabalho\\FRONT END DEFINITIVO");
        } catch (IOException ex) {
            Logger.getLogger(Menu_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_help_btnActionPerformed

    private void bloc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloc_btnActionPerformed
       
    }//GEN-LAST:event_bloc_btnActionPerformed

    private void calc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_btnActionPerformed
        
    }//GEN-LAST:event_calc_btnActionPerformed

    private void consulta_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta_agendaActionPerformed
        new Consulta_GUI().setVisible(true);
    }//GEN-LAST:event_consulta_agendaActionPerformed

    private void Add_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_agendaActionPerformed
        new Adicionar_GUI().setVisible(true);
    }//GEN-LAST:event_Add_agendaActionPerformed

    private void alterar_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_agendaActionPerformed
        new Alterar_GUI().setVisible(true);
    }//GEN-LAST:event_alterar_agendaActionPerformed

    private void excluir_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_agendaActionPerformed
        new Excluir_GUI().setVisible(true);
    }//GEN-LAST:event_excluir_agendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Add_agenda;
    private javax.swing.JMenuItem Encerrar_btn;
    private javax.swing.JMenuItem alterar_agenda;
    private javax.swing.JMenuItem bloc_btn;
    private javax.swing.JMenuItem calc_btn;
    private javax.swing.JMenuItem consulta_agenda;
    private javax.swing.JMenuItem excluir_agenda;
    private javax.swing.JMenuItem help_btn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Panel panel1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
